name: tourist_guide
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:  
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  easy_localization: ^3.0.7
  fluttermoji: ^1.0.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/en.json
    - assets/translations/ar.json
fonts:
  - family: PlaywriteAUSA
    fonts:
      - asset: fonts/PlaywriteAUSA/PlaywriteAUSA-Regular.ttf

  - family: Bitter
    fonts:
      - asset: fonts/Bitter/Bitter-Regular.ttf
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package
