name: tourist_guide
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  fluttermoji: ^1.0.2
  image_picker: ^1.1.2
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/en.json
    - assets/translations/ar.json
    - data_source/gov_data.json
    - data_source/places_data.json
fonts:
  - family: PlaywriteAUSA
    fonts:
      - asset: fonts/PlaywriteAUSA/PlaywriteAUSA-Regular.ttf

  - family: Bitter
    fonts:
      - asset: fonts/Bitter/Bitter-Regular.ttf

# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package
flutter_native_splash:
  android: true
  ios: false
  web: true
  image: assets/images/splash.png
  color: "#d4e4de"
  android_gravity: fill
  fullscreen: true
  android_12:
    color: "#d4e4de"
    image: assets/images/splash.png
    android_gravity: fill
    android_v2: true
