// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjAVrcwDijQQlECAqBHEhZ1ek8JrWRJHA',
    appId: '1:898404056801:web:e3754048ea57828f3e01a0',
    messagingSenderId: '898404056801',
    projectId: 'sprints-tourist-guide',
    authDomain: 'sprints-tourist-guide.firebaseapp.com',
    storageBucket: 'sprints-tourist-guide.firebasestorage.app',
    measurementId: 'G-1W33L3G1JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0to8qcKwvApjlTIi894TckfrbecLvM6w',
    appId: '1:898404056801:android:34fa76412436e1493e01a0',
    messagingSenderId: '898404056801',
    projectId: 'sprints-tourist-guide',
    storageBucket: 'sprints-tourist-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxohZBSR9QChhoKMc3RJG9opm6SrWCYf8',
    appId: '1:898404056801:ios:b99404e2d19ddced3e01a0',
    messagingSenderId: '898404056801',
    projectId: 'sprints-tourist-guide',
    storageBucket: 'sprints-tourist-guide.firebasestorage.app',
    iosBundleId: 'com.example.touristGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxohZBSR9QChhoKMc3RJG9opm6SrWCYf8',
    appId: '1:898404056801:ios:b99404e2d19ddced3e01a0',
    messagingSenderId: '898404056801',
    projectId: 'sprints-tourist-guide',
    storageBucket: 'sprints-tourist-guide.firebasestorage.app',
    iosBundleId: 'com.example.touristGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjAVrcwDijQQlECAqBHEhZ1ek8JrWRJHA',
    appId: '1:898404056801:web:f47d1f42526ea6203e01a0',
    messagingSenderId: '898404056801',
    projectId: 'sprints-tourist-guide',
    authDomain: 'sprints-tourist-guide.firebaseapp.com',
    storageBucket: 'sprints-tourist-guide.firebasestorage.app',
    measurementId: 'G-D5XZK6Y909',
  );
}
